// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ClimbSpeed
 */
export const ClimbSpeed = {
    NA: 'na',
    FAST: 'fast',
    MODERATE: 'moderate',
    SLOW: 'slow'
} as const;

/**
 * ClimbSpeed
 */
export type ClimbSpeed = typeof ClimbSpeed[keyof typeof ClimbSpeed];

/**
 * ClimbSuccess
 */
export const ClimbSuccess = {
    NA: 'na',
    FAIL_1: 'fail-1',
    FAIL_2: 'fail-2',
    SUCCESS: 'success'
} as const;

/**
 * ClimbSuccess
 */
export type ClimbSuccess = typeof ClimbSuccess[keyof typeof ClimbSuccess];

/**
 * Event
 */
export type Event = {
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name: string;
    event_type: EventType;
    /**
     * Week
     */
    week: number;
    /**
     * Year
     */
    year: number;
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date: Date;
    /**
     * District
     */
    district: string;
    /**
     * City
     */
    city: string;
    /**
     * State Prov
     */
    state_prov: string;
    /**
     * Country
     */
    country: string;
};

/**
 * EventIndex
 */
export type EventIndex = {
    /**
     * Name
     */
    name: string;
    /**
     * Key
     */
    key: string;
};

/**
 * EventType
 *
 * An enumeration for event type.
 *
 * Members:
 * INVALID: The event is invalid for some reason.
 * REGIONAL: The event is a traditional regional event.
 * DISTRICT: The event is a district qualifying event.
 * DISTRICT_CMP: The event is a distict championship event.
 * CMP_DIV: The event is a division at the world championship.
 * EINSTEIN: The event is the Einstein final at world championship.
 * DISTRICT_CMP_DIV: The event is a district championship division.
 * OFFSEASON: The event is an offseason event.
 */
export const EventType = {
    '-1': -1,
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    99: 99
} as const;

/**
 * EventType
 *
 * An enumeration for event type.
 *
 * Members:
 * INVALID: The event is invalid for some reason.
 * REGIONAL: The event is a traditional regional event.
 * DISTRICT: The event is a district qualifying event.
 * DISTRICT_CMP: The event is a distict championship event.
 * CMP_DIV: The event is a division at the world championship.
 * EINSTEIN: The event is the Einstein final at world championship.
 * DISTRICT_CMP_DIV: The event is a district championship division.
 * OFFSEASON: The event is an offseason event.
 */
export type EventType = typeof EventType[keyof typeof EventType];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Index
 */
export type Index = {
    /**
     * Events
     */
    events: Array<EventIndex>;
    /**
     * Teams
     */
    teams: Array<EventIndex>;
};

/**
 * Match
 */
export type Match = {
    /**
     * Key
     */
    key: string;
    /**
     * Event Key
     */
    event_key: string;
    /**
     * Set Number
     */
    set_number: number;
    /**
     * Number
     */
    number: number;
    /**
     * Type
     */
    type: 'INVALID' | 'QUAL' | 'EIGHTH' | 'QUARTER' | 'SEMI' | 'FINAL';
    /**
     * Status
     */
    status: 'UPCOMING' | 'COMPLETED';
    /**
     * Time
     */
    time: Date;
    /**
     * Actual Time
     */
    actual_time: Date;
    /**
     * Predicted Time
     */
    predicted_time: Date;
    red_alliance: MatchAlliance;
    blue_alliance: MatchAlliance;
    /**
     * Winner
     */
    winner: 'RED' | 'BLUE' | 'TIE' | 'NOT_PLAYED';
    /**
     * Video
     */
    video: string;
    red_breakdown: MatchBreakdown;
    blue_breakdown: MatchBreakdown;
};

/**
 * MatchAlliance
 */
export type MatchAlliance = {
    /**
     * Teams
     */
    teams: Array<string>;
    /**
     * Dq
     */
    dq: Array<string>;
    /**
     * Backups
     */
    backups: Array<string>;
};

/**
 * MatchBreakdown
 */
export type MatchBreakdown = {
    /**
     * Score
     */
    score: number;
    /**
     * No Foul Points
     */
    no_foul_points: number | null;
    /**
     * Foul Points
     */
    foul_points: number | null;
    /**
     * Auto Points
     */
    auto_points: number | null;
    /**
     * Teleop Points
     */
    teleop_points: number | null;
    /**
     * Endgame Points
     */
    endgame_points: number | null;
    /**
     * Endgame 1
     */
    endgame_1: number | null;
    /**
     * Endgame 2
     */
    endgame_2: number | null;
    /**
     * Endgame 3
     */
    endgame_3: number | null;
    /**
     * Rp 1
     */
    rp_1: boolean | null;
    /**
     * Rp 2
     */
    rp_2: boolean | null;
    /**
     * Rp 3
     */
    rp_3: boolean | null;
    /**
     * Comp 1
     */
    comp_1: number | null;
    /**
     * Comp 2
     */
    comp_2: number | null;
    /**
     * Comp 3
     */
    comp_3: number | null;
    /**
     * Comp 4
     */
    comp_4: number | null;
    /**
     * Comp 5
     */
    comp_5: number | null;
    /**
     * Comp 6
     */
    comp_6: number | null;
    /**
     * Comp 7
     */
    comp_7: number | null;
    /**
     * Comp 8
     */
    comp_8: number | null;
    /**
     * Comp 9
     */
    comp_9: number | null;
    /**
     * Comp 10
     */
    comp_10: number | null;
    /**
     * Comp 11
     */
    comp_11: number | null;
    /**
     * Comp 12
     */
    comp_12: number | null;
    /**
     * Comp 13
     */
    comp_13: number | null;
    /**
     * Comp 14
     */
    comp_14: number | null;
    /**
     * Comp 15
     */
    comp_15: number | null;
    /**
     * Comp 16
     */
    comp_16: number | null;
    /**
     * Comp 17
     */
    comp_17: number | null;
    /**
     * Comp 18
     */
    comp_18: number | null;
};

/**
 * MatchScouting
 */
export type MatchScouting = {
    /**
     * Event Key
     */
    event_key: string;
    /**
     * Team Number
     */
    team_number: number;
    /**
     * Match Number
     */
    match_number: number;
    /**
     * Auto L4
     */
    auto_l4: number;
    /**
     * Auto L3
     */
    auto_l3: number;
    /**
     * Auto L2
     */
    auto_l2: number;
    /**
     * Auto L1
     */
    auto_l1: number;
    /**
     * Teleop L4
     */
    teleop_l4: number;
    /**
     * Teleop L3
     */
    teleop_l3: number;
    /**
     * Teleop L2
     */
    teleop_l2: number;
    /**
     * Teleop L1
     */
    teleop_l1: number;
    /**
     * Miss L4
     */
    miss_l4: number;
    /**
     * Miss L3
     */
    miss_l3: number;
    /**
     * Miss L2
     */
    miss_l2: number;
    /**
     * Miss L1
     */
    miss_l1: number;
    /**
     * Barge Make
     */
    barge_make: number;
    /**
     * Barge Fail
     */
    barge_fail: number;
    climb_success: ClimbSuccess;
    climb_speed: ClimbSpeed;
    /**
     * Superlatives
     */
    superlatives: Array<string>;
    /**
     * Optional Comments
     */
    optional_comments: string;
};

/**
 * SimpleEvent
 */
export type SimpleEvent = {
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name: string;
    /**
     * Start Date
     */
    start_date: Date;
};

/**
 * Team
 */
export type Team = {
    /**
     * Key
     */
    key: string;
    /**
     * Number
     */
    number: number;
    /**
     * Name
     */
    name: string;
    /**
     * Rookie Year
     */
    rookie_year: number;
    /**
     * District
     */
    district: string | null;
    /**
     * City
     */
    city: string;
    /**
     * State Prov
     */
    state_prov: string;
    /**
     * Country
     */
    country: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetByKeyData = {
    body?: never;
    path: {
        /**
         * Event Key
         */
        event_key: string;
    };
    query?: never;
    url: '/event/{event_key}';
};

export type GetByKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByKeyError = GetByKeyErrors[keyof GetByKeyErrors];

export type GetByKeyResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type GetByKeyResponse = GetByKeyResponses[keyof GetByKeyResponses];

export type GetByTeamAndYearData = {
    body?: never;
    path: {
        /**
         * Number
         */
        number: number;
        /**
         * Year
         */
        year: number;
    };
    query?: never;
    url: '/team/{number}/events/{year}';
};

export type GetByTeamAndYearErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByTeamAndYearError = GetByTeamAndYearErrors[keyof GetByTeamAndYearErrors];

export type GetByTeamAndYearResponses = {
    /**
     * Response Getbyteamandyear
     *
     * Successful Response
     */
    200: Event;
};

export type GetByTeamAndYearResponse = GetByTeamAndYearResponses[keyof GetByTeamAndYearResponses];

export type GetByTeamAndYearSimpleData = {
    body?: never;
    path: {
        /**
         * Number
         */
        number: number;
        /**
         * Year
         */
        year: number;
    };
    query?: never;
    url: '/team/{number}/events/{year}/simple';
};

export type GetByTeamAndYearSimpleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByTeamAndYearSimpleError = GetByTeamAndYearSimpleErrors[keyof GetByTeamAndYearSimpleErrors];

export type GetByTeamAndYearSimpleResponses = {
    /**
     * Response Getbyteamandyearsimple
     *
     * Successful Response
     */
    200: SimpleEvent;
};

export type GetByTeamAndYearSimpleResponse = GetByTeamAndYearSimpleResponses[keyof GetByTeamAndYearSimpleResponses];

export type GetByTeamAndEventData = {
    body?: never;
    path: {
        /**
         * Number
         */
        number: number;
        /**
         * Event Key
         */
        event_key: string;
    };
    query?: never;
    url: '/team/{number}/event/{event_key}/matches';
};

export type GetByTeamAndEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByTeamAndEventError = GetByTeamAndEventErrors[keyof GetByTeamAndEventErrors];

export type GetByTeamAndEventResponses = {
    /**
     * Response Getbyteamandevent
     *
     * Successful Response
     */
    200: Match;
};

export type GetByTeamAndEventResponse = GetByTeamAndEventResponses[keyof GetByTeamAndEventResponses];

export type GetMatchesByYearData = {
    body?: never;
    path: {
        /**
         * Number
         */
        number: number;
        /**
         * Year
         */
        year: number;
    };
    query?: never;
    url: '/team/{number}/matches/{year}';
};

export type GetMatchesByYearErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMatchesByYearError = GetMatchesByYearErrors[keyof GetMatchesByYearErrors];

export type GetMatchesByYearResponses = {
    /**
     * Response Getmatchesbyyear
     *
     * Successful Response
     */
    200: Match;
};

export type GetMatchesByYearResponse = GetMatchesByYearResponses[keyof GetMatchesByYearResponses];

export type AddMatchData = {
    body: MatchScouting;
    path?: never;
    query?: never;
    url: '/scouting/add';
};

export type AddMatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMatchError = AddMatchErrors[keyof AddMatchErrors];

export type AddMatchResponses = {
    /**
     * Successful Response
     */
    200: MatchScouting;
};

export type AddMatchResponse = AddMatchResponses[keyof AddMatchResponses];

export type SearchIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/search/index';
};

export type SearchIndexResponses = {
    /**
     * Successful Response
     */
    200: Index;
};

export type SearchIndexResponse = SearchIndexResponses[keyof SearchIndexResponses];

export type BoostrapTeamsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tba/teams';
};

export type BoostrapTeamsResponses = {
    /**
     * Response Boostrapteams
     *
     * Successful Response
     */
    201: string;
};

export type BoostrapTeamsResponse = BoostrapTeamsResponses[keyof BoostrapTeamsResponses];

export type BoostrapEventsData = {
    body?: never;
    path: {
        /**
         * Year
         */
        year: number;
    };
    query?: never;
    url: '/tba/events/{year}';
};

export type BoostrapEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BoostrapEventsError = BoostrapEventsErrors[keyof BoostrapEventsErrors];

export type BoostrapEventsResponses = {
    /**
     * Response Boostrapevents
     *
     * Successful Response
     */
    201: string;
};

export type BoostrapEventsResponse = BoostrapEventsResponses[keyof BoostrapEventsResponses];

export type BoostrapMatchesData = {
    body?: never;
    path: {
        /**
         * Year
         */
        year: number;
    };
    query?: never;
    url: '/tba/matches/{year}';
};

export type BoostrapMatchesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BoostrapMatchesError = BoostrapMatchesErrors[keyof BoostrapMatchesErrors];

export type BoostrapMatchesResponses = {
    /**
     * Response Boostrapmatches
     *
     * Successful Response
     */
    201: string;
};

export type BoostrapMatchesResponse = BoostrapMatchesResponses[keyof BoostrapMatchesResponses];

export type GetByNumberData = {
    body?: never;
    path: {
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/team/{number}';
};

export type GetByNumberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByNumberError = GetByNumberErrors[keyof GetByNumberErrors];

export type GetByNumberResponses = {
    /**
     * Successful Response
     */
    200: Team;
};

export type GetByNumberResponse = GetByNumberResponses[keyof GetByNumberResponses];
