github.com:
    git_protocol: ssh
    users:
        R1shy:
            oauth_token: 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
    user: R1shy
    oauth_token: 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
