// This file is auto-generated by @hey-api/openapi-ts

import type { GetByKeyResponse, GetByTeamAndEventResponse, GetByTeamAndYearResponse, GetByTeamAndYearSimpleResponse, GetMatchesByYearResponse } from './types.gen';

const eventSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    data.end_date = new Date(data.end_date);
    return data;
};

export const getByKeyResponseTransformer = async (data: any): Promise<GetByKeyResponse> => {
    data = eventSchemaResponseTransformer(data);
    return data;
};

export const getByTeamAndYearResponseTransformer = async (data: any): Promise<GetByTeamAndYearResponse> => {
    data = eventSchemaResponseTransformer(data);
    return data;
};

const simpleEventSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    return data;
};

export const getByTeamAndYearSimpleResponseTransformer = async (data: any): Promise<GetByTeamAndYearSimpleResponse> => {
    data = simpleEventSchemaResponseTransformer(data);
    return data;
};

const matchSchemaResponseTransformer = (data: any) => {
    data.time = new Date(data.time);
    data.actual_time = new Date(data.actual_time);
    data.predicted_time = new Date(data.predicted_time);
    return data;
};

export const getByTeamAndEventResponseTransformer = async (data: any): Promise<GetByTeamAndEventResponse> => {
    data = matchSchemaResponseTransformer(data);
    return data;
};

export const getMatchesByYearResponseTransformer = async (data: any): Promise<GetMatchesByYearResponse> => {
    data = matchSchemaResponseTransformer(data);
    return data;
};
